apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefiles-std-static-rwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sc-azurefiles-std-static