apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefiles-std-static-sc
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-azurefiles-std-static
  azureFile:
    secretName: k8sworkshop-static-sa-azure-secret
    shareName: static-pv-example-02/redis-data
    readOnly: false