apiVersion: v1
kind: Pod
metadata:
  name: redis-emptydir
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage-emptydir
      mountPath: /data/redis
  volumes:
  - name: redis-storage-emptydir
    emptyDir: {}