apiVersion: v1
kind: Pod
metadata:
  name: redis-hostpath
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage-hostpath
      mountPath: /data/redis
  volumes:
  - name: redis-storage-hostpath
    hostPath:
      path: /tmp/local-pv