apiVersion: v1
kind: Pod
metadata:
  name: redis-azure-files-std-pvc-example-01-pod
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: dynamic-pv
      mountPath: /data/redis
  volumes:
  - name: dynamic-pv
    persistentVolumeClaim:
        claimName: pvc-azurefiles-std-dynamic