apiVersion: v1
kind: Pod
metadata:
  name: redis-pvc-azurefiles-std-dynamic-rwo-pod
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: azurefiles-std
      mountPath: /data/redis
  nodeSelector:
    kubernetes.io/hostname: k8s-linuxpool-23226980-1
  volumes:
  - name: azurefiles-std
    persistentVolumeClaim:
        claimName: pvc-azurefiles-std-dynamic-rwo