kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-azuredisk-premium-managed-dynamic
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_LRS
  location: westeurope
  kind: Managed