apiVersion: v1
kind: Pod
metadata:
  name: redis-azure-files-std-dynamic-pvc
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: k8sworkshop
      mountPath: /data/redis
  volumes:
  - name: k8sworkshop
    persistentVolumeClaim:
        claimName: pvc-azurefiles-std-dynamic