apiVersion: v1
kind: Pod
metadata:
  name: redis-pvc-disk-std-managed-pod
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: managed-standard
      mountPath: /data/redis
  volumes:
  - name: managed-standard
    persistentVolumeClaim:
        claimName: pvc-azuredisk-std-managed-dynamic 