apiVersion: v1
kind: Pod
metadata:
  name: redis-azure-files-std-static-rwo-pvc-02
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: k8sworkshop
      mountPath: /data/redis
  nodeSelector:
    kubernetes.io/hostname: k8s-linuxpool-23226980-2    
  volumes:
  - name: k8sworkshop
    persistentVolumeClaim:
        claimName: pvc-azurefiles-std-static-rwo