apiVersion: v1
kind: Secret
metadata:
  name: k8sworkshop-dynamic-sa-azure-secret
type: Opaque
data:
  azurestorageaccountname: azhzd29ya3Nob3BkeW5hbWlj
  azurestorageaccountkey: DeLqc4TMTkAiATAs8DibNbP4aagzT35dDspeUXRhwc/AGyAXiBz16ooXoSFz5QozyZA0Ide4S6yxcZYLlmq5+w==